import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          <div className="flex min-h-screen">
            {/* Desktop Sidebar */}
            <div className="hidden min-[450px]:block bg-gray-200">
              <Sidebar />
            </div>
            <div className="flex-1 max-[450px]:p-1 p-2 sm:p-4 bg-gray-100 overflow-y-auto scroll-smooth scrollbar-hide">
              {/* Mobile Sidebar */}
              <div className="min-[450px]:hidden bg-gray-200 mb-1 ">
                <Sidebar />
              </div>
              {children}
            </div>
          </div>
          <Toaster position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}
